Allow banning clients not connected to the server
AttorneyOnline/akashi pull request #138
Opened 2021-06-10 04:38 UTC by MangosArentLiterature

Allows you to ban any IPID, regardless of whether it is connected to the server or not. To accomplish this, IPIDs are used for IP bans instead of remote IPs.

In addition, this PR cleans up both isIPBanned() and isHDIDBanned() by removing extraneous DB queries. It removes getBanDuration and getBanReason, and instead isIPBanned and isHDIDBanned() will retrieve this info in it's single query.

Closes #96

2021-06-13 03:24 UTC, in1tiate approved these changes
looks gucci

2021-06-22 02:49 UTC, scatterflower requested changes

2021-06-22 02:49 UTC, scatterflower commented on core/include/db_manager.h
> +    std::pair<bool, QString> isIPBanned(QString ipid);
Use a QPair

2021-06-22 02:49 UTC, scatterflower commented on core/src/db_manager.cpp
> +std::pair<bool, QString> DBManager::isIPBanned(QString ipid)
QPair

2021-06-22 02:49 UTC, scatterflower commented on core/src/db_manager.cpp
> +    query.prepare("SELECT * FROM BANS WHERE IPID = ? ORDER BY TIME DESC");
instead of selecting *, only select the fields you need

2021-06-22 02:49 UTC, scatterflower commented on core/src/db_manager.cpp
> +std::pair<bool, QString> DBManager::isHDIDBanned(QString hdid)
QPair

2021-06-22 02:49 UTC, scatterflower commented on core/src/db_manager.cpp
> +    query.prepare("SELECT * FROM BANS WHERE HDID = ? ORDER BY TIME DESC");
Ditto previous comment about selecting *

2021-06-22 03:25 UTC, merged