Implement HTTP server advertiser
AttorneyOnline/akashi pull request #152
Opened 2021-07-08 21:23 UTC by Salanto

Attempt to implements server advertiser as described in AttorneyOnline/AO2-Client#550.
The former attempt was too merge conflicted to salvage.

2021-07-09 12:35 UTC, in1tiate approved these changes
my sleep deprived brain sees no problem with this. @scatterflower second opinion please

2021-07-10 14:05 UTC, Cerapter requested changes

2021-07-10 14:05 UTC, Cerapter commented on core/src/http_advertiser.cpp
> +    m_manager = new QNetworkAccessManager();
This will probably not get deleted later.
May wanna make a destructor for HTTPAdvertiser, and deleteLater() this, I think.

2021-07-10 14:05 UTC, Cerapter commented on core/src/http_advertiser.cpp
> +        QNetworkRequest request((QUrl (m_masterserver)));
More brackets than when a 4channer thinks they're cleverly calling out Jewish people on Twitter.

```suggestion
        QNetworkRequest request(QUrl(m_masterserver));
```

2021-07-10 14:05 UTC, Cerapter commented on core/src/http_advertiser.cpp
> +        if (!(m_ws_port == -1)) {
```suggestion
        if (m_ws_port != -1) {
```

2021-07-10 14:05 UTC, Cerapter commented on core/src/http_advertiser.cpp
> +        if (!(m_description.isEmpty())) {
```suggestion
        if (!m_description.isEmpty()) {
```

2021-07-11 18:18 UTC, Cerapter approved these changes

2021-07-12 20:23 UTC, merged