Implement ban webhook
AttorneyOnline/akashi pull request #164
Opened 2021-07-31 13:35 UTC by Salanto

and you can actually turn it off!

2021-07-31 16:14 UTC, in1tiate requested changes

2021-07-31 16:14 UTC, in1tiate commented on core/include/discord.h
> +     * @brief Handles a modcall webhook request.
🤔

2021-07-31 16:14 UTC, in1tiate commented on core/src/discord.cpp
> +        {"title", "User has been banned by " + f_moderator},
```suggestion
        {"title", "Ban issued by " + f_moderator},
```
"User" is nonspecific and awkward

2021-08-01 11:46 UTC, Salanto commented on core/include/discord.h
> +     * @brief Handles a modcall webhook request.
![image](https://user-images.githubusercontent.com/62221668/127769695-c834a7bd-4e3f-4e9e-b3ad-480a0568e73f.png)

2021-08-01 14:44 UTC, in1tiate approved these changes
looks fine

2021-08-01 14:45 UTC, in1tiate commented
@scatterflower new feature, want your approval first

2021-08-02 21:45 UTC, scatterflower commented
needs a squash

2021-08-02 21:53 UTC, merged