Add a check for file writability to the DB to confuse users slightly less.
AttorneyOnline/akashi pull request #180
Opened 2021-08-08 05:59 UTC by t-h-i-s-u-s-e-r-n-a-m-e-i-s-c-a-n-c-e-r

I didn't find a Qt way of doing this quickly enough so I used access(). Hope that's OK.

2021-08-08 14:34 UTC, oldmud0 requested changes
Read the docs. Use QFileInfo::permission.

2021-08-08 14:52 UTC, t-h-i-s-u-s-e-r-n-a-m-e-i-s-c-a-n-c-e-r commented
Sure, but I'd need to check if we're the owner or in the owners group, just seems unnecessary to me.

2021-08-08 21:19 UTC, Salanto commented on core/src/db_manager.cpp
> +    QFileInfo *db_info = new QFileInfo;
Wouldn't a local variable work here too? Why a pointer?

2021-08-09 02:33 UTC, oldmud0 commented on core/src/db_manager.cpp
> +
```suggestion
    const QString db_filename = "config/akashi.db";
    QFileInfo db_info(db_filename);
    if(!db_info.isReadable() || !db_info.isWritable()) 
        qCritical() << tr("Database Error: Missing permissions. Check if \"%1\" is writable.").arg(db_filename);

```

2021-08-10 04:08 UTC, oldmud0 approved these changes

2021-08-10 21:59 UTC, merged