Merge pending changes into master
AttorneyOnline/akashi pull request #271
Opened 2022-06-08 08:39 UTC by Salanto

*Refactors Websocket implementation on Akashi
*Enables per-Area WTCE and Shout control
*Upgrades Akashi to a role-based permission system
*Disables spectators from playing music
*Reworks rate limit for IC messages
*Privatises Server for the most part
*Reworks AOPacket to be a bit cleaner
*Enforces clang-format on the CI and providers QtCreator clang-format file
*Update repository readme
*Enforce handshake checks
*Easier command alias and permission extension feature.

closes #264 
closes #257 
closes #246

2022-06-08 09:23 UTC, in1tiate commented
Oh dear.

2022-06-08 10:17 UTC, in1tiate requested changes
scary diff but most of it is formatting. got some stuff i'd like corrected before i merge this but overall it's really solid

2022-06-08 19:13 UTC, Salanto commented on core/src/aoclient.cpp
> +const QMap<QString, AOClient::CommandInfo> AOClient::COMMANDS{
Not quite able to do this as we need the entire command table on the stack to allocate our alias stuff.

2022-06-13 06:17 UTC, Salanto commented
closes #166 
The original problem seems to have been improper parenting causing edge cases where the client was deleted, but not its corresponding socket.

2022-06-15 22:51 UTC, in1tiate approved these changes
Very, very solid work here. Thank you to all who contributed.

2022-06-15 22:52 UTC, merged