WIP: Help command aliases
AttorneyOnline/akashi pull request #306
Opened 2022-07-03 06:38 UTC by cow-face

Resolves #290

2022-07-03 09:17 UTC, in1tiate submitted a review, later dismissed
Have some minor problems to address, but this looks fine otherwise

2022-07-03 09:17 UTC, in1tiate commented on bin/config_sample/text/commandhelp.json
> +         "area_lock"
Merge this into `/lock` please

2022-07-03 09:17 UTC, in1tiate commented on bin/config_sample/text/commandhelp.json
> +         "area_kick"
Duplicate command

2022-07-03 09:17 UTC, in1tiate commented on bin/config_sample/text/commandhelp.json
> +         "notecard_clear"
Duplicate command

2022-07-03 09:17 UTC, in1tiate commented on bin/config_sample/text/commandhelp.json
>        "usage":"allowblankposting",
```suggestion
      "usage":"/allowblankposting",
```

2022-07-03 09:17 UTC, in1tiate commented on bin/config_sample/text/commandhelp.json
> +         "force_noint_pres"
Merge this into `forceimmediate` please

2022-07-03 09:17 UTC, in1tiate commented on bin/config_sample/text/commandhelp.json
> +         "update_ban"
Merge this into `updateban` please

2022-07-03 14:09 UTC, scatterflower requested changes

2022-07-03 14:09 UTC, scatterflower commented on core/src/config_manager.cpp
> +        QJsonArray l_names = l_child_obj["names"].toArray();
this variable is defined already

2022-07-03 14:09 UTC, scatterflower commented on core/src/config_manager.cpp
> +                help l_help_information;
replace this with inline initialization i.e.

```
help l_help_information = {
     .usage = l_usage,
     .text = l_text
 };```

2022-07-06 14:53 UTC, scatterflower commented
fails tests
```
FAIL!  : tests::unittests::tst_ConfigManager::CommandInfo() Compared values are not the same
   Actual   (l_help.text)            : ""
   Expected ("A sample explanation."): A sample explanation.
   Loc: [tst_unittest_config_manager.cpp(221)]```

2022-07-06 14:55 UTC, scatterflower approved these changes

2022-07-06 14:55 UTC, scatterflower approved these changes

2022-07-06 18:53 UTC, merged