Add /evidence_swap
AttorneyOnline/akashi pull request #37
Opened 2021-03-16 22:17 UTC by Salanto

2021-03-16 22:54 UTC, in1tiate commented on src/commands.cpp
> +    if ((ok && ok2) && (EvID2 <= EvSize) && (EvID1 <= EvSize)) {
what happens if `EvID1` or `EvID2` are negative

2021-03-16 22:55 UTC, in1tiate commented on include/aoclient.h
> +        {"evidence_swap", {ACLFlags.value("CM"), 2, &AOClient::cmdEvidence_Swap}}
```suggestion
        {"evidence_swap", {ACLFlags.value("CM"), 2, &AOClient::cmdEvidence_Swap}},
```
doing this will prevent most merge conflicts

2021-03-17 10:54 UTC, scatterflower requested changes

2021-03-17 10:54 UTC, scatterflower commented on src/commands.cpp
> +    uint EvSize = area->evidence.size()-1;
both of these should be snake_case

2021-03-17 10:54 UTC, scatterflower commented on src/commands.cpp
> +    uint EvSize = area->evidence.size()-1;
also put spaces between operators and operands

2021-03-17 10:54 UTC, scatterflower commented on src/commands.cpp
> +        AreaData::Evidence EvData = area->evidence[EvID1];
snake_case

2021-03-17 10:54 UTC, scatterflower commented on src/commands.cpp
> +        sendServerMessage("The evidence has been swapped.");
Send a more descriptive message, i.e. "evidence 3 and 8 have been swapped"

2021-04-03 08:41 UTC, scatterflower commented
fix the merge conflict and i will merge this

2021-04-03 22:18 UTC, merged