Add two roll command, fix minor formatting on prior commands
AttorneyOnline/akashi pull request #8
Opened 2021-01-30 00:17 UTC by Salanto

In this pull request, I'll be explaining exactly what I do to merge in 0.5 commits. But first, we need to clear something up. Because every time I post a half commit video, I get the same comments over and over asking what it means, even though I always have a whole paragraph in the description explaining it, which even starts with 'If you're wondering what a half commit is, read this before commenting to ask'.

2021-02-25 18:37 UTC, stonedDiscord requested changes

2021-02-25 18:37 UTC, stonedDiscord commented on src/aoclient.cpp
> +    QString hostname = config.value("hostname", "Server").toString();
this is the same code as above and it looks ugly

can you write a method in the server class that gets the hostname for us, or better, one that sends system OOC messages to the specified audience

2021-02-25 18:37 UTC, stonedDiscord commented on src/commands.cpp
> +        if (1 <= amount_faces and amount_faces <= max_roll_faces and 1 <= amount_rolls and amount_rolls <= max_roll_amount)
can you add comments on what these if statements do

2021-02-25 18:37 UTC, stonedDiscord commented on src/commands.cpp
> +            sendServerMessageArea((sender_name + " rolled in secret."));;
this looks a lot like the 3 blocks above it

wouldn't it be cleaner to put dice_results at the top and use a bool if it was secret or not to decide wether to announce the result

2021-02-25 18:37 UTC, stonedDiscord commented on src/commands.cpp
> +    sendServerBroadcast({"=== Advert ===\n[" + sender_area + "] needs " + sender_message+ "."});
(-_-)
-<>-

2021-02-28 23:28 UTC, scatterflower requested changes

2021-02-28 23:28 UTC, scatterflower commented on src/commands.cpp
> +    int max_roll_faces = 11037;
why these numbers? shouldn't they be configurable?

2021-02-28 23:28 UTC, scatterflower commented on src/commands.cpp
> +    int max_roll_faces = 11037;
ditto

2021-02-28 23:54 UTC, scatterflower requested changes

2021-02-28 23:54 UTC, scatterflower commented on src/commands.cpp
> +        if (1 <= amount_faces and amount_faces <= max_roll_faces)
please use &&

2021-03-03 16:05 UTC, scatterflower requested changes

2021-03-03 16:05 UTC, scatterflower commented on include/aoclient.h
> +
Use all-caps for enum members

2021-03-03 16:05 UTC, scatterflower commented on src/commands.cpp
> +
pass the RollType argument like this: `diceThrower(argc, argv, RollType::ROLLP)`

2021-03-03 16:05 UTC, scatterflower commented on src/commands.cpp
> +    }
This looks like it can get really slow, really fast. Has any testing been done on how this performs?

2021-03-03 16:05 UTC, scatterflower commented on src/commands.cpp
> +    int max_roll_amount = server->getDiceValue("max_dices");
plural of die is dice, not dices

2021-03-03 16:46 UTC, scatterflower commented on src/commands.cpp
> +void AOClient::diceThrower(int argc, QStringList argv, RollType Type)
Type should be lowercase `type`

2021-03-03 16:46 UTC, scatterflower commented on src/commands.cpp
> +    if (argc == 0)
For all if and else statements: opening brace goes on the same line as the if
i.e. `if (argc == 0) {`

2021-03-03 16:47 UTC, scatterflower commented on src/server.cpp
> +
`settings.endGroup("Dice");`

2021-03-03 19:43 UTC, merged